---
name: 02 – Workflow Events
on: 
  #push:
  #pull_request: 
  #schedule:
  #  - cron: '32 12 * * *'   #W darmowej wersji cron dziala w nieokreslony sposób 
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Show the trigger"
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo `date`