---
name: 03 – Workflow Runners
on: 
  push:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: Linux
    steps:
      - name: "Show OS"
        run: |
          echo "This job is running on an my runner."
          lsb_release -a > /home/student/osv
          cat /home/student/osv

      
  ubuntu-echo2:
    needs: ubuntu-echo
    runs-on: Linux
    steps:
      - name: "Show OS"
        run: |
          echo "This job is running on an my runner."
          cat /home/student/osv

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: "Show OS"
        run: |
          echo "This job is running on a Windows runner."
          Get-ComputerInfo | select-object OsName,OSDisplayVersion

  mac-echo:
    runs-on: macos-latest
    steps:
      - name: "Show OS"
        run: |
          echo "This job is running on a MacOS runner."
          sw_vers